### ISSUE TITLE
RNA Transcription Test Results in Error

### ISSUE THREAD

**Issue by andrewfgarrison** [exercism/dart-test-runner#26]
I have attempted to submit a solution for the "RNA Transcription" problem in the Dart track, and confirmed locally that there are no issues with my code and that all tests pass successfully. However, upon submitting/testing in editor, the result is the "an error occurred" message, stating that something in the code is causing the CLI to return an error. I have looked at my own code, but I can see nothing that would cause an error, so I believe this is caused by a version difference.

[rna_transcription.txt](https://github.com/exercism/dart-test-runner/files/7102450/rna_transcription.txt)
![image](https://user-images.githubusercontent.com/64180300/131930802-f4f65f24-3a05-4598-a8e1-35af6ee3050b.png)

**Comment by Stargator** [comment]
@andrewfgarrison It's hard to tell from just one file. But there may be a few factors at play.

If you could either push everything you have (minus the `.dart` folder and `.packages` file) to a repository or zip it up, that may help me test this.

Also, what is the current version of Dart you are using?

**Comment by andrewfgarrison** [comment]
Thank you for your response, I confirmed that I am using version 2.13.4 of Dart through Flutter (2.2.3). I also ran the `dart pub upgrade --precompile` and `dart run test --run-skipped` commands, but all tests passed without issue.

For now, I'll attach a zip file of the problem folder, but if you would like me to send more, please let me know!
[rna-transcription.zip](https://github.com/exercism/dart-test-runner/files/7103614/rna-transcription.zip)

**Comment by Stargator** [comment]
@andrewfgarrison Thank you, I'll go ahead and test this with 2.13.4 of Dart

**Comment by Stargator** [comment]
@andrewfgarrison I can't find any issue with your code. You mentioned the editor was throwing an error. Exercism's editor?

Can you share the full message?

**Comment by Stargator** [comment]
@andrewfgarrison I have a possible solution in the works in #28

**Comment by andrewfgarrison** [comment]
I sincerely apologize for the delay, I just retried running the tests in the site editor, and everything passed without issue. I did not change any of my code, so I assume the issue was resolved. Thank you very much!

**Comment by Stargator** [comment]
@andrewfgarrison Glad to hear it's been resolved. Let us know if anything like this happens again
