### ISSUE TITLE
Unexplained errors

### ISSUE THREAD

**Issue by MSoup** [exercism/dart-test-runner#31]
Apart from hello world, every problem I have attempted so far results in an error that doesn't provide guidance on where to look. For example, here is my code for two fer:

```
String twoFer([String? name = 'you']) {
  return "One for ${name}, one for me.";
}
```

Apart from any glaring flaws I might have in my code (or do I have any?), the test tab shows:

```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

Is there something I'm doing wrong? On my CLI, my tests pass, but it seems like my submission is incorrect when I test it on the site.

**Comment by Stargator** [comment]
Moved this to the dart-test-runner since we believe that is the root of the issue.

**Comment by iHiD** [comment]
@Stargator Shout if you need any more data. If you let me know handle/exercise/iteration-id, I can get you stdout, stderr, etc.

**Comment by Stargator** [comment]
> @Stargator Shout if you need any more data. If you let me know handle/exercise/iteration-id, I can get you stdout, stderr, etc.

Did you send me the logs? Sorry, I thought I accepted your prior offer.

**Comment by iHiD** [comment]
This is on a hello-world for me, which times out:

stderr:
```
Warning: Upgrading when offline may not update you to the latest versions of your dependencies.
```

stdout:
```
hello-world: testing...
```

**Comment by Stargator** [comment]
> This is on a hello-world for me, which times out:
> 
> stderr:
> ```
> Warning: Upgrading when offline may not update you to the latest versions of your dependencies.
> ```
> 
> stdout:
> ```
> hello-world: testing...
> ```

The stderr is expected as we are running upgrade with --offline.

No other details for when the test is running?

**Comment by iHiD** [comment]
Sadly not. That's all that the test runner seems to output. All we know around this is that at 10s it's not finished and so the container gets killed. But Erik gets the same running it locally in docker, so I think it's an issue with how it's running in docker?
